// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMarkdown(arg1) {
  return window['go']['markdown']['Markdown']['GetMarkdown'](arg1);
}

export function SaveMarkdown(arg1, arg2) {
  return window['go']['markdown']['Markdown']['SaveMarkdown'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['markdown']['Markdown']['Startup'](arg1);
}
